import Foundation
import Supabase

public final class SupabaseInviteService: InviteServiceProtocol {
    private var client: SupabaseClient {
        SupabaseManager.shared.client
    }

    public init() {}

    /// `code` and `uses_count` are absent on purpose: neither column is granted to
    /// `authenticated`, so the code is always generated by the database.
    private struct InviteInsert: Encodable {
        let chapter_id: UUID
        let created_by: UUID
        let expires_at: Date?
        let max_uses: Int?
    }

    private struct RevokeUpdate: Encodable {
        let revoked_at: Date
    }

    private struct RedeemParams: Encodable {
        let p_code: String
    }

    public func fetchInvites(for chapterId: UUID) async throws -> [ChapterInvite] {
        try await client
            .from("chapter_invite")
            .select()
            .eq("chapter_id", value: chapterId)
            .order("created_at", ascending: false)
            .execute()
            .value
    }

    public func createInvite(chapterId: UUID, createdBy: UUID, expiresAt: Date?, maxUses: Int?) async throws -> ChapterInvite {
        let payload = InviteInsert(
            chapter_id: chapterId,
            created_by: createdBy,
            expires_at: expiresAt,
            max_uses: maxUses
        )

        return try await client
            .from("chapter_invite")
            .insert(payload)
            .select()
            .single()
            .execute()
            .value
    }

    public func revokeInvite(id: UUID) async throws {
        try await client
            .from("chapter_invite")
            .update(RevokeUpdate(revoked_at: Date()))
            .eq("id", value: id)
            .execute()
    }

    /// Goes through the RPC because the redeemer can neither read an invite for a
    /// chapter they are outside of nor insert their own membership.
    public func redeem(code: String) async throws -> ChapterMembership {
        let membership: ChapterMembership = try await client
            .rpc("redeem_chapter_invite", params: RedeemParams(p_code: InviteCode.normalize(code)))
            .single()
            .execute()
            .value

        WidgetManager.shared.reloadTimelines()
        return membership
    }
}
